APP_NAME = "Grey vless"
APP_ID = "com.grey.vless"
PACKAGE_NAME = "grey-vless"
INSTALL_DIR = "/opt/grey-vless"
USER_AGENT = "GreyVless/1.0"
APP_VERSION = "0.4.14+18"
GITHUB_REPO = "GermannM3/grey-vless"
