import '../models/server.dart';

const _flags = {
  'финлянд': '🇫🇮',
  'finland': '🇫🇮',
  'fin': '🇫🇮',
  'поль': '🇵🇱',
  'poland': '🇵🇱',
  'pol': '🇵🇱',
  'франц': '🇫🇷',
  'france': '🇫🇷',
  'fra': '🇫🇷',
  'нидерланд': '🇳🇱',
  'netherlands': '🇳🇱',
  'holland': '🇳🇱',
  'nld': '🇳🇱',
  'латви': '🇱🇻',
  'latvia': '🇱🇻',
  'lva': '🇱🇻',
  'герман': '🇩🇪',
  'germany': '🇩🇪',
  'deu': '🇩🇪',
  'deutsch': '🇩🇪',
  'росс': '🇷🇺',
  'russia': '🇷🇺',
  'rus': '🇷🇺',
  'сша': '🇺🇸',
  'usa': '🇺🇸',
  'united states': '🇺🇸',
  'америк': '🇺🇸',
  'великобрит': '🇬🇧',
  'uk': '🇬🇧',
  'britain': '🇬🇧',
  'england': '🇬🇧',
  'gbr': '🇬🇧',
  'англ': '🇬🇧',
  'турц': '🇹🇷',
  'turkey': '🇹🇷',
  'tur': '🇹🇷',
  'япон': '🇯🇵',
  'japan': '🇯🇵',
  'jpn': '🇯🇵',
  'коре': '🇰🇷',
  'korea': '🇰🇷',
  'kor': '🇰🇷',
  'сингапур': '🇸🇬',
  'singapore': '🇸🇬',
  'sgp': '🇸🇬',
  'канада': '🇨🇦',
  'canada': '🇨🇦',
  'can': '🇨🇦',
  'швец': '🇸🇪',
  'sweden': '🇸🇪',
  'swe': '🇸🇪',
  'норвег': '🇳🇴',
  'norway': '🇳🇴',
  'nor': '🇳🇴',
  'испан': '🇪🇸',
  'spain': '🇪🇸',
  'esp': '🇪🇸',
  'итал': '🇮🇹',
  'italy': '🇮🇹',
  'ita': '🇮🇹',
  'украин': '🇺🇦',
  'ukraine': '🇺🇦',
  'ukr': '🇺🇦',
  'казах': '🇰🇿',
  'kazakh': '🇰🇿',
  'kaz': '🇰🇿',
  'инд': '🇮🇳',
  'india': '🇮🇳',
  'ind': '🇮🇳',
  'австрал': '🇦🇺',
  'australia': '🇦🇺',
  'aus': '🇦🇺',
  'бразил': '🇧🇷',
  'brazil': '🇧🇷',
  'bra': '🇧🇷',
  'молд': '🇲🇩',
  'moldova': '🇲🇩',
  'mda': '🇲🇩',
  'румын': '🇷🇴',
  'romania': '🇷🇴',
  'rou': '🇷🇴',
  'чех': '🇨🇿',
  'czech': '🇨🇿',
  'cze': '🇨🇿',
  'австр': '🇦🇹',
  'austria': '🇦🇹',
  'aut': '🇦🇹',
  'швейц': '🇨🇭',
  'switzerland': '🇨🇭',
  'che': '🇨🇭',
  'болгар': '🇧🇬',
  'bulgaria': '🇧🇬',
  'bgr': '🇧🇬',
  'груз': '🇬🇪',
  'georgia': '🇬🇪',
  'geo': '🇬🇪',
  'армен': '🇦🇲',
  'armenia': '🇦🇲',
  'arm': '🇦🇲',
  'израил': '🇮🇱',
  'israel': '🇮🇱',
  'isr': '🇮🇱',
  'оаэ': '🇦🇪',
  'uae': '🇦🇪',
  'are': '🇦🇪',
  'эстон': '🇪🇪',
  'estonia': '🇪🇪',
  'est': '🇪🇪',
  'литв': '🇱🇹',
  'lithuania': '🇱🇹',
  'ltu': '🇱🇹',
  'бел': '🇧🇾',
  'belarus': '🇧🇾',
  'blr': '🇧🇾',
  'hong': '🇭🇰',
  'гонконг': '🇭🇰',
  'hkg': '🇭🇰',
  'тайван': '🇹🇼',
  'taiwan': '🇹🇼',
  'twn': '🇹🇼',
  'китай': '🇨🇳',
  'china': '🇨🇳',
  'chn': '🇨🇳',
};

const _tldFlags = {
  'fi': '🇫🇮',
  'pl': '🇵🇱',
  'fr': '🇫🇷',
  'nl': '🇳🇱',
  'lv': '🇱🇻',
  'de': '🇩🇪',
  'ru': '🇷🇺',
  'us': '🇺🇸',
  'uk': '🇬🇧',
  'gb': '🇬🇧',
  'tr': '🇹🇷',
  'jp': '🇯🇵',
  'kr': '🇰🇷',
  'sg': '🇸🇬',
  'ca': '🇨🇦',
  'se': '🇸🇪',
  'no': '🇳🇴',
  'es': '🇪🇸',
  'it': '🇮🇹',
  'ua': '🇺🇦',
  'kz': '🇰🇿',
  'in': '🇮🇳',
  'au': '🇦🇺',
  'br': '🇧🇷',
  'md': '🇲🇩',
  'ro': '🇷🇴',
  'cz': '🇨🇿',
  'at': '🇦🇹',
  'ch': '🇨🇭',
  'bg': '🇧🇬',
  'ge': '🇬🇪',
  'am': '🇦🇲',
  'il': '🇮🇱',
  'ae': '🇦🇪',
  'ee': '🇪🇪',
  'lt': '🇱🇹',
  'by': '🇧🇾',
  'hk': '🇭🇰',
  'tw': '🇹🇼',
  'cn': '🇨🇳',
};

String countryFlagFor(String serverName) {
  final lower = serverName.toLowerCase();
  for (final entry in _flags.entries) {
    if (lower.contains(entry.key)) return entry.value;
  }
  return '🌐';
}

String countryFlagForServer(VpnServer server) {
  final fromName = countryFlagFor(server.name);
  if (fromName != '🌐') return fromName;

  for (final host in [server.host, server.params['sni'] ?? '']) {
    if (host.isEmpty) continue;
    final parts = host.split('.');
    if (parts.length >= 2) {
      final tld = parts.last.toLowerCase();
      final flag = _tldFlags[tld];
      if (flag != null) return flag;
    }
    final fromHost = countryFlagFor(host);
    if (fromHost != '🌐') return fromHost;
  }
  return '🌐';
}
