const _flags = {
  'финлянд': '🇫🇮',
  'finland': '🇫🇮',
  'поль': '🇵🇱',
  'poland': '🇵🇱',
  'франц': '🇫🇷',
  'france': '🇫🇷',
  'нидерланд': '🇳🇱',
  'netherlands': '🇳🇱',
  'голland': '🇳🇱',
  'латви': '🇱🇻',
  'latvia': '🇱🇻',
  'герман': '🇩🇪',
  'germany': '🇩🇪',
  'deutsch': '🇩🇪',
  'росс': '🇷🇺',
  'russia': '🇷🇺',
  'сша': '🇺🇸',
  'usa': '🇺🇸',
  'америк': '🇺🇸',
  'великобрит': '🇬🇧',
  'uk': '🇬🇧',
  'britain': '🇬🇧',
  'англ': '🇬🇧',
  'турц': '🇹🇷',
  'turkey': '🇹🇷',
  'япон': '🇯🇵',
  'japan': '🇯🇵',
  'коре': '🇰🇷',
  'korea': '🇰🇷',
  'сингапур': '🇸🇬',
  'singapore': '🇸🇬',
  'канада': '🇨🇦',
  'canada': '🇨🇦',
  'швец': '🇸🇪',
  'sweden': '🇸🇪',
  'норвег': '🇳🇴',
  'norway': '🇳🇴',
  'испан': '🇪🇸',
  'spain': '🇪🇸',
  'итал': '🇮🇹',
  'italy': '🇮🇹',
  'украин': '🇺🇦',
  'ukraine': '🇺🇦',
  'казах': '🇰🇿',
  'kazakh': '🇰🇿',
  'инд': '🇮🇳',
  'india': '🇮🇳',
  'австрал': '🇦🇺',
  'australia': '🇦🇺',
  'бразил': '🇧🇷',
  'brazil': '🇧🇷',
  'молд': '🇲🇩',
  'moldova': '🇲🇩',
  'румын': '🇷🇴',
  'romania': '🇷🇴',
  'чех': '🇨🇿',
  'czech': '🇨🇿',
  'австр': '🇦🇹',
  'austria': '🇦🇹',
  'швейц': '🇨🇭',
  'switzerland': '🇨🇭',
  'болгар': '🇧🇬',
  'bulgaria': '🇧🇬',
  'груз': '🇬🇪',
  'georgia': '🇬🇪',
  'армен': '🇦🇲',
  'armenia': '🇦🇲',
  'израил': '🇮🇱',
  'israel': '🇮🇱',
  'оаэ': '🇦🇪',
  'uae': '🇦🇪',
  'эстон': '🇪🇪',
  'estonia': '🇪🇪',
  'литв': '🇱🇹',
  'lithuania': '🇱🇹',
  'бел': '🇧🇾',
  'belarus': '🇧🇾',
  'hong': '🇭🇰',
  'гонконг': '🇭🇰',
  'тайван': '🇹🇼',
  'taiwan': '🇹🇼',
};

String countryFlagFor(String serverName) {
  final lower = serverName.toLowerCase();
  for (final entry in _flags.entries) {
    if (lower.contains(entry.key)) return entry.value;
  }
  return '🌐';
}
